version: '3.8'

networks:
  app:
    driver: bridge

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - app 
  app:
    depends_on:
      - mysqldb
    build: ./server
    # command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    # restart: unless-stopped
    volumes:
      - "./server:/server"
    #   - "/server/node_modules:/server/node_modules"
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - app 
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    # stdin_open: true
    # tty: true

volumes: 
  db:

