-- MySQL Script generated by MySQL Workbench
-- sáb 09 jul 2022 18:38:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto4a
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto4a
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto4a` ;
USE `projeto4a` ;

-- -----------------------------------------------------
-- Table `projeto4a`.`UnidadeFederacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto4a`.`UnidadeFederacao` (
  `siglaUF` VARCHAR(2) NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`siglaUF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto4a`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto4a`.`Cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(45) NULL,
  `UnidadeFederacao_siglaUF` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`, `UnidadeFederacao_siglaUF`),
  INDEX `fk_Cidade_UnidadeFederacao1_idx` (`UnidadeFederacao_siglaUF` ASC),
  CONSTRAINT `fk_Cidade_UnidadeFederacao1`
    FOREIGN KEY (`UnidadeFederacao_siglaUF`)
    REFERENCES `projeto4a`.`UnidadeFederacao` (`siglaUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto4a`.`TipoLogradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto4a`.`TipoLogradouro` (
  `siglaLogradouro` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`siglaLogradouro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto4a`.`Logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto4a`.`Logradouro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `TipoLogradouro_siglaLogradouro` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`, `TipoLogradouro_siglaLogradouro`),
  INDEX `fk_Logradouro_TipoLogradouro1_idx` (`TipoLogradouro_siglaLogradouro` ASC),
  CONSTRAINT `fk_Logradouro_TipoLogradouro1`
    FOREIGN KEY (`TipoLogradouro_siglaLogradouro`)
    REFERENCES `projeto4a`.`TipoLogradouro` (`siglaLogradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto4a`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto4a`.`Bairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto4a`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto4a`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NULL,
  `Cidade_id` INT NOT NULL,
  `Logradouro_id` INT NOT NULL,
  `Bairro_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Cidade_id`, `Logradouro_id`, `Bairro_id`),
  INDEX `fk_Endereco_Cidade1_idx` (`Cidade_id` ASC),
  INDEX `fk_Endereco_Logradouro1_idx` (`Logradouro_id` ASC),
  INDEX `fk_Endereco_Bairro1_idx` (`Bairro_id` ASC),
  CONSTRAINT `fk_Endereco_Cidade1`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `projeto4a`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Logradouro1`
    FOREIGN KEY (`Logradouro_id`)
    REFERENCES `projeto4a`.`Logradouro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Bairro1`
    FOREIGN KEY (`Bairro_id`)
    REFERENCES `projeto4a`.`Bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto4a`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto4a`.`Empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `cnpj` VARCHAR(45) NULL,
  `numero_casa` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `Endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Endereco_id`),
  INDEX `fk_Empresa_Endereco1_idx` (`Endereco_id` ASC),
  CONSTRAINT `fk_Empresa_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `projeto4a`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto4a`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto4a`.`Conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `saldo_atual` INT ZEROFILL NULL,
  `Empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Empresa_id`),
  INDEX `fk_Conta_Empresa_idx` (`Empresa_id` ASC),
  CONSTRAINT `fk_Conta_Empresa`
    FOREIGN KEY (`Empresa_id`)
    REFERENCES `projeto4a`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto4a`.`Tipo_Transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto4a`.`Tipo_Transacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` ENUM('despesa', 'receita') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto4a`.`Transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto4a`.`Transacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `valor` VARCHAR(45) NULL,
  `numero_documento` VARCHAR(45) NULL,
  `observacao` VARCHAR(255) NULL,
  `saldo` INT NULL,
  `Conta_id` INT NOT NULL,
  `Tipo_Transacao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Conta_id`, `Tipo_Transacao_id`),
  INDEX `fk_Transacao_Conta1_idx` (`Conta_id` ASC),
  INDEX `fk_Transacao_Tipo_Transacao1_idx` (`Tipo_Transacao_id` ASC),
  CONSTRAINT `fk_Transacao_Conta1`
    FOREIGN KEY (`Conta_id`)
    REFERENCES `projeto4a`.`Conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_Tipo_Transacao1`
    FOREIGN KEY (`Tipo_Transacao_id`)
    REFERENCES `projeto4a`.`Tipo_Transacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
